#!/bin/sh
# Merge the doc from master to gh-pages


MARKDOWN="doc/src"
HTML="doc/html"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

BRANCH=`git rev-parse --symbolic --abbrev-ref HEAD`
if [ "$BRANCH" = "master" ]
then
    echo "Update gh-pages with modified documentation"
    git subtree split -q --prefix "$HTML" --branch gh-pages
fi

